[tool.poetry]
name = "litestar"
version = "2.0.0beta2"
description = "Litestar - A production-ready, highly performant, extensible ASGI API Framework"
authors = [
    "Na'aman Hirschfeld <nhirschfeld@gmail.com>",
    "Peter Schutt <peter.github@proton.me>",
    "Cody Fincher <cody.fincher@gmail.com>",
    "Janek Nouvertné <provinzkraut@posteo.de>",
    "Jacob Coffee <jacob@z7x.org>",
]
maintainers = [
    "Na'aman Hirschfeld <nhirschfeld@gmail.com>",
    "Cody Fincher <cody.fincher@gmail.com>",
    "Janek Nouvertné <provinzkraut@posteo.de>",
    "Jacob Coffee <jacob@z7x.org>",
]
license = "MIT"
readme = "docs/PYPI_README.md"
homepage = "https://litestar.dev/"
repository = "https://github.com/litestar-org/litestar"
documentation = "https://docs.litestar.dev/"
keywords = [
    "api",
    "rest",
    "http",
    "asgi",
    "pydantic",
    "litestar",
    "starlite",
    "framework",
    "websocket",
    "litestar",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Framework :: AsyncIO",
    #    Pending trove-classifiers#148
    #    "Framework :: Litestar",
    #    "Framework :: Litestar :: 2",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 1",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = ["CHANGELOG.rst"]
packages = [{ include = "litestar" }]

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/litestar-org/litestar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
"Changelog" = "https://github.com/litestar-org/litestar/releases/"
"Twitter" = "https://twitter.com/LitestarAPI"
"Reddit" = "https://www.reddit.com/r/litestarapi"
"Discord" = "https://discord.gg/MmcwxztmQb"
"Blog" = "https://blog.litestar.dev"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
alembic = { version = "*", optional = true }
annotated-types = { version = "*", optional = true }
anyio = ">=3"
attrs = { version = "*", optional = true }
brotli = { version = "*", optional = true }
click = { version = "*", optional = true }
cryptography = { version = "*", optional = true }
fast-query-parsers = "*"
httpx = ">=0.22"
importlib-metadata = { version = "*", python = "<3.10" }
importlib-resources = { version = ">=5.12.0", python = "<3.9" }
jinja2 = { version = ">=3.1.2", optional = true }
jsbeautifier = { version = "*", optional = true }
mako = { version = ">=1.2.4", optional = true }
msgspec = ">=0.17.0"
multidict = ">=6.0.2"
opentelemetry-instrumentation-asgi = { version = "*", optional = true }
picologging = { version = "*", optional = true }
polyfactory = ">=2.3.2"
prometheus-client = { version = "*", optional = true }
pydantic = "*"
pydantic-extra-types = { version = "*", optional = true }
python-dateutil = "*"
python-jose = { version = "*", optional = true }
pytimeparse = "*"
pyyaml = "*"
redis = { version = ">=4.4.4, <4.5.0", optional = true, extras = ["hiredis"] }
rich = { version = ">=13.0.0", optional = true }
rich-click = { version = "*", optional = true }
sqlalchemy = { version = ">=2.0.12", optional = true }
structlog = { version = "*", optional = true }
tortoise-orm = { version = ">=0.17.0", optional = true }
typing-extensions = "*"
uvicorn = { extras = ["standard"], version = ">=0.22.0", optional = true }

[tool.poetry.group.dev.dependencies]
aiosqlite = "*"
alembic = "*"
annotated-types = "*"
asyncmy = "*"
asyncpg = "*"
attrs = "*"
beanie = "*"
beautifulsoup4 = "*"
brotli = "*"
click = "*"
cryptography = "*"
duckdb-engine = "*"
fakeredis = { extras = ["lua"], version = "*" }
freezegun = "*"
fsspec = "*"
greenlet = "*"
hypothesis = "*"
jinja2 = "*"
jsbeautifier = "*"
mako = "*"
mongomock-motor = { version = "*", markers = "sys_platform != 'win32'" }
opentelemetry-instrumentation-asgi = "*"
opentelemetry-sdk = "*"
oracledb = "*"
piccolo = "*"
picologging = "*"
pre-commit = "*"
prometheus-client = "*"
psycopg = "*"
pydantic = "*"
pydantic-extra-types = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-lazy-fixture = "*"
pytest-mock = "*"
pytest-rerunfailures = "*"
python-dateutil = "*"
python-dotenv = "*"
python-jose = "*"
pytimeparse = "*"
redis = ">=4.4.4, <4.5.0"
rich = "*"
rich-click = "*"
sqlalchemy = ">=2.0"
sqlalchemy-spanner = "*"
starlette = "*"
structlog = "*"
tortoise-orm = "*"
trio = "*"
uvicorn = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
auto-pytabs = { extras = ["sphinx"], version = "*" }
black = "*"
httpx = "*"
sphinx = ">=5.3.0,<=6"
sphinx-autobuild = "*"
sphinx-copybutton = ">=0.5.1"
sphinx-design = ">=0.3.0,<1"
sphinxcontrib-mermaid = ">=0.8.1,<1"
litestar-sphinx-theme = { git = "https://github.com/litestar-org/litestar-sphinx-theme.git" }
uvicorn = "*"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
asyncpg-stubs = "*"
black = "*"
blacken-docs = "*"
mypy = "*"
pyright = "*"
ruff = '*'
slotscheck = "*"
sourcery = "*"
types-beautifulsoup4 = "*"
types-freezegun = "*"
types-python-dateutil = "*"
types-python-jose = "*"
types-pyyaml = "*"
types-redis = "*"

[tool.poetry.extras]
annotated-types = ["annotated-types"]
attrs = ["attrs"]
brotli = ["brotli"]
cli = ["click", "rich", "rich-click", "jsbeautifier", "uvicorn"]
cryptography = ["cryptography"]
jinja = ["jinja2"]
jwt = ["python-jose", "cryptography"]
opentelemetry = ["opentelemetry-instrumentation-asgi"]
picologging = ["picologging"]
prometheus = ["prometheus-client"]
redis = ["redis"]
sqlalchemy = ["sqlalchemy", "alembic"]
standard = ["click", "jinja2", "jsbeautifier", "rich", "uvicorn", "rich-click"]
structlog = ["structlog"]
tortoise-orm = ["tortoise-orm"]

full = [
    "alembic",
    "attrs",
    "brotli",
    "click",
    "cryptography",
    "jinja2",
    "jsbeautifier",
    "opentelemetry-instrumentation-asgi",
    "prometheus-client",
    "python-dateutil",
    "python-jose",
    "pytimeparse",
    "redis",
    "rich",
    "sqlalchemy",
    "structlog",
    "uvicorn",
]

[tool.poetry.scripts]
litestar = { callable = "litestar.__main__:run_cli", extras = ["cli"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.codespell]
ignore-words-list = "selectin"
skip = 'poetry.lock,docs/examples/contrib/sqlalchemy/us_state_lookup.json'

[tool.coverage.run]
omit = ["*/tests/*", "litestar/contrib/sqlalchemy_1/*"]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'if TYPE_CHECKING:',
    'except ImportError as e:',
    'except ImportError:',
    '\.\.\.',
    'raise NotImplementedError',
    'if VERSION.startswith("1"):',
]

[tool.pytest.ini_options]
addopts = "--ignore=examples -m='not sqlalchemy_integration'"
asyncio_mode = "auto"
filterwarnings = [
    "ignore::trio.TrioDeprecationWarning:anyio._backends._trio*:164",
    "ignore::DeprecationWarning:pkg_resources.*",
    "ignore::DeprecationWarning:google.rpc",
    "ignore::DeprecationWarning:google.gcloud",
    "ignore::DeprecationWarning:google.iam",
    "ignore::DeprecationWarning:google",
    "ignore::DeprecationWarning:sphinxcontrib",
    "ignore::DeprecationWarning:litestar.*",
]
markers = [
    "sqlalchemy_integration: SQLAlchemy integration tests",
    "sqlalchemy_asyncmy: SQLAlchemy MySQL (asyncmy) Tests",
    "sqlalchemy_asyncpg: SQLAlchemy Postgres (asyncpg) Tests",
    "sqlalchemy_psycopg_async: SQLAlchemy Postgres (psycopg async) Tests",
    "sqlalchemy_aiosqlite: SQLAlchemy SQLite (aiosqlite) Tests",
    "sqlalchemy_psycopg_sync: SQLAlchemy Postgres (psycopg sync) Tests",
    "sqlalchemy_sqlite: SQLAlchemy SQLite (sqlite) Tests",
    "sqlalchemy_oracledb: SQLAlchemy Oracle (oracledb) Tests",
    "sqlalchemy_spanner: SQLAlchemy Google Cloud Spanner (sqlalchemy-spanner) Tests",
    "sqlalchemy_duckdb: SQLAlchemy Duckdb (duckdb-engine) Tests",
]

[tool.pyright]
include = ["litestar", "tests", "examples"]
exclude = [
    "examples/plugins/sqlalchemy_plugin",
    "litestar/openapi",
    "tests/unit/test_contrib/test_sqlalchemy/test_dto.py",
]

[tool.slotscheck]
strict-imports = false

[tool.ruff]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "BLE", # flake8-blind-except
    "C4",  # flake8-comprehensions
    "C90", # mccabe
    "D",   # pydocstyle
    "DJ",  # flake8-django
    "DTZ", # flake8-datetimez
    "E",   # pycodestyle errors
    "ERA", # eradicate
    "EXE", # flake8-executable
    "F",   # pyflakes
    "G",   # flake8-logging-format
    "I",   # isort
    "ICN", # flake8-import-conventions
    "ISC", # flake8-implicit-str-concat
    "N",   # pep8-naming
    "PIE", # flake8-pie
    "PLC", # pylint - convention
    "PLE", # pylint - error
    "PLW", # pylint - warning
    "PTH", # flake8-use-pathlib
    "Q",   # flake8-quotes
    "RET", # flake8-return
    "RUF", # Ruff-specific rules
    "S",   # flake8-bandit
    "SIM", # flake8-simplify
    "T10", # flake8-debugger
    "T20", # flake8-print
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
    "W",   # pycodestyle - warning
    "YTT", # flake8-2020
]

ignore = [
    "A003",    # flake8-builtins - class attribute {name} is shadowing a python builtin
    "B010",    # flake8-bugbear - do not call setattr with a constant attribute value
    "D100",    # pydocstyle - missing docstring in public module
    "D101",    # pydocstyle - missing docstring in public class
    "D102",    # pydocstyle - missing docstring in public method
    "D103",    # pydocstyle - missing docstring in public function
    "D104",    # pydocstyle - missing docstring in public package
    "D105",    # pydocstyle - missing docstring in magic method
    "D106",    # pydocstyle - missing docstring in public nested class
    "D107",    # pydocstyle - missing docstring in __init__
    "D202",    # pydocstyle - no blank lines allowed after function docstring
    "D205",    # pydocstyle - 1 blank line required between summary line and description
    "D415",    # pydocstyle - first line should end with a period, question mark, or exclamation point
    "E501",    # pycodestyle line too long, handled by black
    "PLW2901", # pylint - for loop variable overwritten by assignment target
    "RUF012",  # Ruff-specific rule - annotated with classvar
]
line-length = 120
src = ["litestar", "tests", "docs/examples"]
target-version = "py38"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.mccabe]
max-complexity = 12

[tool.ruff.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "pydantic.root_validator",
    "pydantic.validator",
    "sqlalchemy.ext.declarative.declared_attr",
    "sqlalchemy.orm.declared_attr.directive",
    "sqlalchemy.orm.declared_attr",
]

[tool.ruff.isort]
known-first-party = ["litestar", "tests", "examples"]

[tool.ruff.per-file-ignores]
"tests/**/*.*" = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C901",
    "D",
    "DTZ",
    "EM",
    "FBT",
    "G",
    "N",
    "PGH",
    "PIE",
    "PLR",
    "PLW",
    "PTH",
    "RSE",
    "S",
    "S101",
    "SIM",
    "TCH",
    "TRY",
]
"tests/unit/test_contrib/test_sqlalchemy/**/*.*" = ["UP006"]
"docs/examples/application_hooks/before_send_hook.py" = ["UP006"]
"docs/examples/contrib/sqlalchemy/plugins/**/*.*" = ["UP006"]
"docs/**/*.*" = ["S", "B", "DTZ", "A", "TCH", "ERA", "D", "RET"]
"docs/examples/**" = ["T201"]
"docs/examples/data_transfer_objects**/*.*" = ["UP006"]
"litestar/exceptions/*.*" = ["N818"]
"litestar/handlers/**/*.*" = ["N801"]
"litestar/_openapi/schema_generation/schema.py" = ["C901"]
"litestar/params.py" = ["N802"]
"test_apps/**/*.*" = ["D", "TRY", "EM", "S", "PTH"]
"tools/**/*.*" = ["D", "ARG", "EM", "TRY", "G", "FBT"]

[tool.unasyncd]
add_editors_note = true
ruff_fix = true

[tool.unasyncd.files]
"litestar/contrib/sqlalchemy/repository/_async.py" = "litestar/contrib/sqlalchemy/repository/_sync.py"
"litestar/contrib/repository/abc/_async.py" = "litestar/contrib/repository/abc/_sync.py"

[tool.unasyncd.per_file_add_replacements."litestar/contrib/repository/abc/_async.py"]
"AbstractAsyncRepository" = "AbstractSyncRepository"
"AsyncRepoT" = "SyncRepoT"

[tool.unasyncd.per_file_add_replacements."litestar/contrib/sqlalchemy/repository/_async.py"]
SQLAlchemyAsyncRepository = "SQLAlchemySyncRepository"
"sqlalchemy.ext.asyncio.AsyncSession" = "sqlalchemy.orm.Session"
"litestar.contrib.repository.AbstractAsyncRepository" = "litestar.contrib.repository.AbstractSyncRepository"
